@startuml
'https://plantuml.com/sequence-diagram

actor e as "employee"

rectangle Database

' define the usecase

rectangle "Information System"{
    usecase uc as "Send the request"
    usecase gi1 as "get the information"
    usecase gi2 as "get the information"
    usecase condition1 as "sort from largest to smallest population"
    usecase condition2 as "N provied by the User"
    usecase print as "Print Report/Data"

' define the relationship between the usecases
    e - uc

    uc ..> gi1: include
    uc ..> condition2: include
    gi1 ..> condition1: include
    condition2 ..> gi2: include
    condition1 ..> print : extend
    gi2 ..> print : extend
    uc ..> print : extend
    uc - Database: extend

}

@enduml